### ISSUE TITLE
Failed to follow "Read data from an IOC" section of tutorials

### ISSUE THREAD

**Issue by Hep-dog** [dls-controls/pythonSoftIOC#16]
Hi all,
After creating a cothread IOC, I tried to read data in another shell. But I got the following error :
![image](https://user-images.githubusercontent.com/17798127/124539973-16225c80-de51-11eb-89a5-d9a14b3c35eb.png)

I also tried to use the epics.PV.get, and it was worked:
![image](https://user-images.githubusercontent.com/17798127/124540079-479b2800-de51-11eb-934a-6d0e426c7e05.png)

I don't know why, and will be very grateful for your help. Thansk a lot!

**Comment by Araneidae** [comment]
Chances are you have a local firewall blocking ports 5064 and 5065.

Note that you do have to run the IOC process by running `softioc.interactive_ioc()` after creating the PVs before they are visible from outside.

**Comment by thomascobb** [comment]
Another thing to try, if you remove the `from softioc import softioc` in your client, what happens?

**Comment by thomascobb** [comment]
Also, what OS and architecture is the machine you're running on?

**Comment by Araneidae** [comment]
Closing as unable to reproduce and no response from reporter.
