### ISSUE TITLE
Improving code coverage

### ISSUE THREAD

**Issue by Araneidae** [dls-controls/pythonSoftIOC#24]
Looking at, for example [Codecov:device.py](https://codecov.io/gh/dls-controls/pythonSoftIOC/src/master/softioc/device.py), there is some low hanging fruit that could easily be added to the tests.

- Setting the alarm with `.set_alarm()` and reading back the currently set value on an In record with `.get()`; both these functions are simple to call and check for side effects.
- I'm a little surprised to see that we have no Out records without `on_update` set (this would cover [L106](https://codecov.io/gh/dls-controls/pythonSoftIOC/src/master/softioc/device.py#L106))
- Are we actually triggering Out record processing, or has the code coverage engine failed to spot that lines 130 to 146 are being executed?
- Are we testing calling `.set()` on Out records at all?  This would trigger a lot of code that's uncovered at present.

**Comment by thomascobb** [comment]
> Are we actually triggering Out record processing, or has the code coverage engine failed to spot that lines 130 to 146 are being executed?

We're triggering it, but the first function called from C doesn't get recorded in the coverage. Now I've added an `ao.set()` then it gets recorded as covered via that.
