### ISSUE TITLE
Be able to force Out records into an error state

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [dls-controls/pythonSoftIOC#53]
Currently there is no explicit way to force an Out record into an error state. The `set()` method on In records provides the `severity` and `alarm` keyword arguments (as well as the `set_alarm()` method), but there is no equivalent mechanism for Out records. Providing this would be useful for the PandABlocks-client PythonSoftIOC integration, as PandA can report fields as being in_error, and the associated records are often Out types.

**Comment by evalott100** [comment]
@AlexanderWells-diamond

Was there any progress on this? We need it for [this](https://github.com/PandABlocks/PandABlocks-ioc/issues/107).

**Comment by AlexanderWells-diamond** [comment]
@Araneidae and I have just discussed this. In principle we can do it. 

There are some behavioural questions though, such as whether this alarm should be "sticky" or whether it should clear on next write, that sort of thing. Could you give us an example of what you'd want/expect to see, assuming we invent some `.set_alarm()` method on out records?

**Comment by Araneidae** [comment]
It's worth pointing out that doing this requires a hack and is not directly supported by EPICS.

**Comment by evalott100** [comment]
The use case we're looking at is when the PandABlocks ioc stops receiving data from the client. We don't want to end the process, but mirror what other iocs do - keep the PVs active and in an error state.

![image](https://github.com/dls-controls/pythonSoftIOC/assets/21142790/9236084c-c112-4fba-9b12-974436ca06cf)

`$ caget PANDA1:CALC2:INPA.STAT`
> `PANDA1:CALC2:INPA.STAT         NO_ALARM`


`$ caget PANDA1:CALC2:OUT.STAT`
> `PANDA1:CALC2:OUT.STAT          READ_ACCESS`
