### ISSUE TITLE
Naming convention inconsistency

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [dls-controls/pythonSoftIOC#75]
There's a small naming convention inconsistency with the names of the record types: Action, WaveformIn and WaveformOut are all PascalCase, and every other record is camelCase (aOut, mbbIn, etc.).

On a related note, WaveformIn is defined slightly differently to WaveformOut - it's actually "Waveform" - which causes `__name__` to show an unexpected string, and IDE intellisense to highlight it differently

This naming convention has been around for some time, and so changing it would be potentially disruptive.

**Comment by thomascobb** [comment]
> On a related note, WaveformIn is defined slightly differently to WaveformOut - it's actually "Waveform" - which causes name to show an unexpected string, and IDE intellisense to highlight it differently

We could swap the alias `WaveformIn` with the definition `Waveform` without breaking anything. We could also change the names and provide aliases to the old ones, but I'm curious as to whether the different names are deliberate.

@Araneidae was there a reason for choosing `builder.WaveformOut` over `builder.waveformOut` like `builder.longOut`?

Personally I prefer to follow PEP8 which would be `builder.waveform_out` but that's probably a step too far

**Comment by Araneidae** [comment]
The reason I used `Waveform` rather than `waveform` was to avoid confusion with the `records.waveform` constructor, and I used camelCase for all the others for historical reasons.

I'd rather not change the names.

**Comment by Araneidae** [comment]
Don't think this is worth worrying about!
